// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use glib::{GStr};

#[doc(alias = "IBUS_INTERFACE_CONFIG")]
pub static INTERFACE_CONFIG: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_CONFIG)};
#[doc(alias = "IBUS_INTERFACE_ENGINE")]
pub static INTERFACE_ENGINE: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_ENGINE)};
#[doc(alias = "IBUS_INTERFACE_FACTORY")]
pub static INTERFACE_FACTORY: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_FACTORY)};
#[doc(alias = "IBUS_INTERFACE_IBUS")]
pub static INTERFACE_IBUS: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_IBUS)};
#[doc(alias = "IBUS_INTERFACE_INPUT_CONTEXT")]
pub static INTERFACE_INPUT_CONTEXT: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_INPUT_CONTEXT)};
#[doc(alias = "IBUS_INTERFACE_NOTIFICATIONS")]
pub static INTERFACE_NOTIFICATIONS: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_NOTIFICATIONS)};
#[doc(alias = "IBUS_INTERFACE_PANEL")]
pub static INTERFACE_PANEL: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_PANEL)};
#[doc(alias = "IBUS_INTERFACE_PORTAL")]
pub static INTERFACE_PORTAL: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_INTERFACE_PORTAL)};
#[doc(alias = "IBUS_PATH_CONFIG")]
pub static PATH_CONFIG: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_PATH_CONFIG)};
#[doc(alias = "IBUS_PATH_FACTORY")]
pub static PATH_FACTORY: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_PATH_FACTORY)};
#[doc(alias = "IBUS_PATH_IBUS")]
pub static PATH_IBUS: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_PATH_IBUS)};
#[doc(alias = "IBUS_PATH_INPUT_CONTEXT")]
pub static PATH_INPUT_CONTEXT: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_PATH_INPUT_CONTEXT)};
#[doc(alias = "IBUS_PATH_NOTIFICATIONS")]
pub static PATH_NOTIFICATIONS: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_PATH_NOTIFICATIONS)};
#[doc(alias = "IBUS_PATH_PANEL")]
pub static PATH_PANEL: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_PATH_PANEL)};
#[doc(alias = "IBUS_PATH_PANEL_EXTENSION_EMOJI")]
pub static PATH_PANEL_EXTENSION_EMOJI: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_PATH_PANEL_EXTENSION_EMOJI)};
#[doc(alias = "IBUS_SERVICE_CONFIG")]
pub static SERVICE_CONFIG: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_SERVICE_CONFIG)};
#[doc(alias = "IBUS_SERVICE_IBUS")]
pub static SERVICE_IBUS: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_SERVICE_IBUS)};
#[doc(alias = "IBUS_SERVICE_NOTIFICATIONS")]
pub static SERVICE_NOTIFICATIONS: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_SERVICE_NOTIFICATIONS)};
#[doc(alias = "IBUS_SERVICE_PANEL")]
pub static SERVICE_PANEL: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_SERVICE_PANEL)};
#[doc(alias = "IBUS_SERVICE_PANEL_EXTENSION")]
pub static SERVICE_PANEL_EXTENSION: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_SERVICE_PANEL_EXTENSION)};
#[doc(alias = "IBUS_SERVICE_PANEL_EXTENSION_EMOJI")]
pub static SERVICE_PANEL_EXTENSION_EMOJI: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_SERVICE_PANEL_EXTENSION_EMOJI)};
#[doc(alias = "IBUS_SERVICE_PORTAL")]
pub static SERVICE_PORTAL: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::IBUS_SERVICE_PORTAL)};
