// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use crate::{Object,Property,Serializable};
use glib::{prelude::*,translate::*};
use std::{fmt};

glib::wrapper! {
    #[doc(alias = "IBusPropList")]
    pub struct PropList(Object<ffi::IBusPropList, ffi::IBusPropListClass>) @extends Serializable, Object;

    match fn {
        type_ => || ffi::ibus_prop_list_get_type(),
    }
}

impl PropList {
        pub const NONE: Option<&'static PropList> = None;
    

    #[doc(alias = "ibus_prop_list_new")]
    pub fn new() -> PropList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::ibus_prop_list_new())
        }
    }
}

impl Default for PropList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

pub trait PropListExt: 'static {
    #[doc(alias = "ibus_prop_list_append")]
    fn append(&self, prop: &impl IsA<Property>);

    #[doc(alias = "ibus_prop_list_get")]
    fn get(&self, index: u32) -> Option<Property>;

    #[doc(alias = "ibus_prop_list_update_property")]
    fn update_property(&self, prop: &impl IsA<Property>) -> bool;
}

impl<O: IsA<PropList>> PropListExt for O {
    fn append(&self, prop: &impl IsA<Property>) {
        unsafe {
            ffi::ibus_prop_list_append(self.as_ref().to_glib_none().0, prop.as_ref().to_glib_none().0);
        }
    }

    fn get(&self, index: u32) -> Option<Property> {
        unsafe {
            from_glib_none(ffi::ibus_prop_list_get(self.as_ref().to_glib_none().0, index))
        }
    }

    fn update_property(&self, prop: &impl IsA<Property>) -> bool {
        unsafe {
            from_glib(ffi::ibus_prop_list_update_property(self.as_ref().to_glib_none().0, prop.as_ref().to_glib_none().0))
        }
    }
}

impl fmt::Display for PropList {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("PropList")
    }
}
