// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use crate::{Object,Serializable};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_,fmt,mem::transmute};

glib::wrapper! {
    #[doc(alias = "IBusUnicodeBlock")]
    pub struct UnicodeBlock(Object<ffi::IBusUnicodeBlock, ffi::IBusUnicodeBlockClass>) @extends Serializable, Object;

    match fn {
        type_ => || ffi::ibus_unicode_block_get_type(),
    }
}

impl UnicodeBlock {
        pub const NONE: Option<&'static UnicodeBlock> = None;
    

    //#[doc(alias = "ibus_unicode_block_new")]
    //pub fn new(first_property_name: &str, : /*Unknown conversion*//*Unimplemented*/Basic: VarArgs) -> UnicodeBlock {
    //    unsafe { TODO: call ffi:ibus_unicode_block_new() }
    //}

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`UnicodeBlock`] objects.
            ///
            /// This method returns an instance of [`UnicodeBlockBuilder`](crate::builders::UnicodeBlockBuilder) which can be used to create [`UnicodeBlock`] objects.
            pub fn builder() -> UnicodeBlockBuilder {
                UnicodeBlockBuilder::new()
            }
        

    #[doc(alias = "ibus_unicode_block_load")]
    pub fn load(path: &str) -> Vec<UnicodeBlock> {
        assert_initialized_main_thread!();
        unsafe {
            FromGlibPtrContainer::from_glib_full(ffi::ibus_unicode_block_load(path.to_glib_none().0))
        }
    }
}

impl Default for UnicodeBlock {
                     fn default() -> Self {
                         glib::object::Object::new::<Self>()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`UnicodeBlock`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct UnicodeBlockBuilder {
            builder: glib::object::ObjectBuilder<'static, UnicodeBlock>,
        }

        impl UnicodeBlockBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            pub fn end(self, end: u32) -> Self {
                            Self { builder: self.builder.property("end", end), }
                        }

                            pub fn name(self, name: impl Into<glib::GString>) -> Self {
                            Self { builder: self.builder.property("name", name.into()), }
                        }

                            pub fn start(self, start: u32) -> Self {
                            Self { builder: self.builder.property("start", start), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`UnicodeBlock`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> UnicodeBlock {
    self.builder.build() }
}

pub trait UnicodeBlockExt: 'static {
    #[doc(alias = "ibus_unicode_block_get_end")]
    #[doc(alias = "get_end")]
    fn end(&self) -> char;

    #[doc(alias = "ibus_unicode_block_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString>;

    #[doc(alias = "ibus_unicode_block_get_start")]
    #[doc(alias = "get_start")]
    fn start(&self) -> char;

    fn set_name(&self, name: Option<&str>);

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<UnicodeBlock>> UnicodeBlockExt for O {
    fn end(&self) -> char {
        unsafe {
            std::convert::TryFrom::try_from(ffi::ibus_unicode_block_get_end(self.as_ref().to_glib_none().0)).expect("conversion from an invalid Unicode value attempted")
        }
    }

    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::ibus_unicode_block_get_name(self.as_ref().to_glib_none().0))
        }
    }

    fn start(&self) -> char {
        unsafe {
            std::convert::TryFrom::try_from(ffi::ibus_unicode_block_get_start(self.as_ref().to_glib_none().0)).expect("conversion from an invalid Unicode value attempted")
        }
    }

    fn set_name(&self, name: Option<&str>) {
        glib::ObjectExt::set_property(self.as_ref(),"name", &name)
    }

    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<UnicodeBlock>, F: Fn(&P) + 'static>(this: *mut ffi::IBusUnicodeBlock, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(UnicodeBlock::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::name\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_name_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for UnicodeBlock {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("UnicodeBlock")
    }
}
