// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "IBusAttrList", sizeof(IBusAttrList), alignof(IBusAttrList));
    printf("%s;%zu;%zu\n", "IBusAttrListClass", sizeof(IBusAttrListClass), alignof(IBusAttrListClass));
    printf("%s;%zu;%zu\n", "IBusAttrType", sizeof(IBusAttrType), alignof(IBusAttrType));
    printf("%s;%zu;%zu\n", "IBusAttrUnderline", sizeof(IBusAttrUnderline), alignof(IBusAttrUnderline));
    printf("%s;%zu;%zu\n", "IBusAttribute", sizeof(IBusAttribute), alignof(IBusAttribute));
    printf("%s;%zu;%zu\n", "IBusAttributeClass", sizeof(IBusAttributeClass), alignof(IBusAttributeClass));
    printf("%s;%zu;%zu\n", "IBusBus", sizeof(IBusBus), alignof(IBusBus));
    printf("%s;%zu;%zu\n", "IBusBusClass", sizeof(IBusBusClass), alignof(IBusBusClass));
    printf("%s;%zu;%zu\n", "IBusBusNameFlag", sizeof(IBusBusNameFlag), alignof(IBusBusNameFlag));
    printf("%s;%zu;%zu\n", "IBusBusRequestNameReply", sizeof(IBusBusRequestNameReply), alignof(IBusBusRequestNameReply));
    printf("%s;%zu;%zu\n", "IBusBusStartServiceByNameReply", sizeof(IBusBusStartServiceByNameReply), alignof(IBusBusStartServiceByNameReply));
    printf("%s;%zu;%zu\n", "IBusCapabilite", sizeof(IBusCapabilite), alignof(IBusCapabilite));
    printf("%s;%zu;%zu\n", "IBusComponent", sizeof(IBusComponent), alignof(IBusComponent));
    printf("%s;%zu;%zu\n", "IBusComponentClass", sizeof(IBusComponentClass), alignof(IBusComponentClass));
    printf("%s;%zu;%zu\n", "IBusConfig", sizeof(IBusConfig), alignof(IBusConfig));
    printf("%s;%zu;%zu\n", "IBusConfigClass", sizeof(IBusConfigClass), alignof(IBusConfigClass));
    printf("%s;%zu;%zu\n", "IBusConfigService", sizeof(IBusConfigService), alignof(IBusConfigService));
    printf("%s;%zu;%zu\n", "IBusConfigServiceClass", sizeof(IBusConfigServiceClass), alignof(IBusConfigServiceClass));
    printf("%s;%zu;%zu\n", "IBusEmojiData", sizeof(IBusEmojiData), alignof(IBusEmojiData));
    printf("%s;%zu;%zu\n", "IBusEmojiDataClass", sizeof(IBusEmojiDataClass), alignof(IBusEmojiDataClass));
    printf("%s;%zu;%zu\n", "IBusEngine", sizeof(IBusEngine), alignof(IBusEngine));
    printf("%s;%zu;%zu\n", "IBusEngineClass", sizeof(IBusEngineClass), alignof(IBusEngineClass));
    printf("%s;%zu;%zu\n", "IBusEngineDesc", sizeof(IBusEngineDesc), alignof(IBusEngineDesc));
    printf("%s;%zu;%zu\n", "IBusEngineDescClass", sizeof(IBusEngineDescClass), alignof(IBusEngineDescClass));
    printf("%s;%zu;%zu\n", "IBusEngineSimple", sizeof(IBusEngineSimple), alignof(IBusEngineSimple));
    printf("%s;%zu;%zu\n", "IBusEngineSimpleClass", sizeof(IBusEngineSimpleClass), alignof(IBusEngineSimpleClass));
    printf("%s;%zu;%zu\n", "IBusError", sizeof(IBusError), alignof(IBusError));
    printf("%s;%zu;%zu\n", "IBusExtensionEvent", sizeof(IBusExtensionEvent), alignof(IBusExtensionEvent));
    printf("%s;%zu;%zu\n", "IBusExtensionEventClass", sizeof(IBusExtensionEventClass), alignof(IBusExtensionEventClass));
    printf("%s;%zu;%zu\n", "IBusFactory", sizeof(IBusFactory), alignof(IBusFactory));
    printf("%s;%zu;%zu\n", "IBusFactoryClass", sizeof(IBusFactoryClass), alignof(IBusFactoryClass));
    printf("%s;%zu;%zu\n", "IBusHotkeyProfile", sizeof(IBusHotkeyProfile), alignof(IBusHotkeyProfile));
    printf("%s;%zu;%zu\n", "IBusHotkeyProfileClass", sizeof(IBusHotkeyProfileClass), alignof(IBusHotkeyProfileClass));
    printf("%s;%zu;%zu\n", "IBusInputContext", sizeof(IBusInputContext), alignof(IBusInputContext));
    printf("%s;%zu;%zu\n", "IBusInputContextClass", sizeof(IBusInputContextClass), alignof(IBusInputContextClass));
    printf("%s;%zu;%zu\n", "IBusInputHints", sizeof(IBusInputHints), alignof(IBusInputHints));
    printf("%s;%zu;%zu\n", "IBusInputPurpose", sizeof(IBusInputPurpose), alignof(IBusInputPurpose));
    printf("%s;%zu;%zu\n", "IBusKeymap", sizeof(IBusKeymap), alignof(IBusKeymap));
    printf("%s;%zu;%zu\n", "IBusKeymapClass", sizeof(IBusKeymapClass), alignof(IBusKeymapClass));
    printf("%s;%zu;%zu\n", "IBusLookupTable", sizeof(IBusLookupTable), alignof(IBusLookupTable));
    printf("%s;%zu;%zu\n", "IBusLookupTableClass", sizeof(IBusLookupTableClass), alignof(IBusLookupTableClass));
    printf("%s;%zu;%zu\n", "IBusModifierType", sizeof(IBusModifierType), alignof(IBusModifierType));
    printf("%s;%zu;%zu\n", "IBusObject", sizeof(IBusObject), alignof(IBusObject));
    printf("%s;%zu;%zu\n", "IBusObjectClass", sizeof(IBusObjectClass), alignof(IBusObjectClass));
    printf("%s;%zu;%zu\n", "IBusObjectFlags", sizeof(IBusObjectFlags), alignof(IBusObjectFlags));
    printf("%s;%zu;%zu\n", "IBusObservedPath", sizeof(IBusObservedPath), alignof(IBusObservedPath));
    printf("%s;%zu;%zu\n", "IBusObservedPathClass", sizeof(IBusObservedPathClass), alignof(IBusObservedPathClass));
    printf("%s;%zu;%zu\n", "IBusOrientation", sizeof(IBusOrientation), alignof(IBusOrientation));
    printf("%s;%zu;%zu\n", "IBusPanelService", sizeof(IBusPanelService), alignof(IBusPanelService));
    printf("%s;%zu;%zu\n", "IBusPanelServiceClass", sizeof(IBusPanelServiceClass), alignof(IBusPanelServiceClass));
    printf("%s;%zu;%zu\n", "IBusPreeditFocusMode", sizeof(IBusPreeditFocusMode), alignof(IBusPreeditFocusMode));
    printf("%s;%zu;%zu\n", "IBusProcessKeyEventData", sizeof(IBusProcessKeyEventData), alignof(IBusProcessKeyEventData));
    printf("%s;%zu;%zu\n", "IBusPropList", sizeof(IBusPropList), alignof(IBusPropList));
    printf("%s;%zu;%zu\n", "IBusPropListClass", sizeof(IBusPropListClass), alignof(IBusPropListClass));
    printf("%s;%zu;%zu\n", "IBusPropState", sizeof(IBusPropState), alignof(IBusPropState));
    printf("%s;%zu;%zu\n", "IBusPropType", sizeof(IBusPropType), alignof(IBusPropType));
    printf("%s;%zu;%zu\n", "IBusProperty", sizeof(IBusProperty), alignof(IBusProperty));
    printf("%s;%zu;%zu\n", "IBusPropertyClass", sizeof(IBusPropertyClass), alignof(IBusPropertyClass));
    printf("%s;%zu;%zu\n", "IBusProxy", sizeof(IBusProxy), alignof(IBusProxy));
    printf("%s;%zu;%zu\n", "IBusProxyClass", sizeof(IBusProxyClass), alignof(IBusProxyClass));
    printf("%s;%zu;%zu\n", "IBusRectangle", sizeof(IBusRectangle), alignof(IBusRectangle));
    printf("%s;%zu;%zu\n", "IBusRegistry", sizeof(IBusRegistry), alignof(IBusRegistry));
    printf("%s;%zu;%zu\n", "IBusRegistryClass", sizeof(IBusRegistryClass), alignof(IBusRegistryClass));
    printf("%s;%zu;%zu\n", "IBusSerializable", sizeof(IBusSerializable), alignof(IBusSerializable));
    printf("%s;%zu;%zu\n", "IBusSerializableClass", sizeof(IBusSerializableClass), alignof(IBusSerializableClass));
    printf("%s;%zu;%zu\n", "IBusService", sizeof(IBusService), alignof(IBusService));
    printf("%s;%zu;%zu\n", "IBusServiceClass", sizeof(IBusServiceClass), alignof(IBusServiceClass));
    printf("%s;%zu;%zu\n", "IBusText", sizeof(IBusText), alignof(IBusText));
    printf("%s;%zu;%zu\n", "IBusTextClass", sizeof(IBusTextClass), alignof(IBusTextClass));
    printf("%s;%zu;%zu\n", "IBusUnicodeBlock", sizeof(IBusUnicodeBlock), alignof(IBusUnicodeBlock));
    printf("%s;%zu;%zu\n", "IBusUnicodeBlockClass", sizeof(IBusUnicodeBlockClass), alignof(IBusUnicodeBlockClass));
    printf("%s;%zu;%zu\n", "IBusUnicodeData", sizeof(IBusUnicodeData), alignof(IBusUnicodeData));
    printf("%s;%zu;%zu\n", "IBusUnicodeDataClass", sizeof(IBusUnicodeDataClass), alignof(IBusUnicodeDataClass));
    printf("%s;%zu;%zu\n", "IBusXEvent", sizeof(IBusXEvent), alignof(IBusXEvent));
    printf("%s;%zu;%zu\n", "IBusXEventClass", sizeof(IBusXEventClass), alignof(IBusXEventClass));
    printf("%s;%zu;%zu\n", "IBusXEventType", sizeof(IBusXEventType), alignof(IBusXEventType));
    printf("%s;%zu;%zu\n", "IBusXML", sizeof(IBusXML), alignof(IBusXML));
    return 0;
}
